// ═══════════════════════════════════════════════════════════════════════════
// AUTO-GENERATED by training/train_models.py — DO NOT EDIT MANUALLY
// Real feature importance, correlation matrix, and population stats
// computed from 25,328 training samples across 4 clinical datasets.
// ═══════════════════════════════════════════════════════════════════════════

const COMPUTED_FEATURE_IMPORTANCE = [
  {
    "feature": "BMI",
    "importance": 0.2375,
    "category": "Physiological"
  },
  {
    "feature": "CVD History",
    "importance": 0.2241,
    "category": "Medical History"
  },
  {
    "feature": "Hypertension History",
    "importance": 0.2231,
    "category": "Medical History"
  },
  {
    "feature": "Blood Glucose",
    "importance": 0.1847,
    "category": "Physiological"
  },
  {
    "feature": "Age",
    "importance": 0.1143,
    "category": "Demographics"
  },
  {
    "feature": "Smoking Status",
    "importance": 0.0115,
    "category": "Lifestyle"
  },
  {
    "feature": "Gender",
    "importance": 0.0047,
    "category": "Demographics"
  }
];

const COMPUTED_CORRELATION = {
  labels: ["Age", "BMI", "Glucose", "Hypertension", "CVD Hx", "Smoking"],
  matrix: [[1.0, 0.04, 0.14, 0.27, 0.32, 0.06], [0.04, 1.0, 0.08, 0.02, -0.07, 0.05], [0.14, 0.08, 1.0, -0.02, 0.04, 0.02], [0.27, 0.02, -0.02, 1.0, -0.07, 0.04], [0.32, -0.07, 0.04, -0.07, 1.0, 0.07], [0.06, 0.05, 0.02, 0.04, 0.07, 1.0]]
};

const COMPUTED_CLASS_DISTRIBUTION = {
  "t2dm": 5000,
  "hypertension": 3725,
  "cvd": 4145,
  "stroke": 1000,
  "metabolic": 1458,
  "obesity": 5000,
  "healthy": 5000
};

const COMPUTED_BMI_STATS = {
  "mean": 30.5,
  "std": 7.2,
  "bins": [
    15,
    20,
    25,
    30,
    35,
    40,
    45,
    50
  ],
  "counts": [
    1039,
    3164,
    9431,
    6103,
    3024,
    1426,
    603
  ]
};
